RANK=0 INTERMEDIATE_SIZE=6400 CUDA_VISIBLE_DEVICES=0 WORLD_SIZE=4 python tune_kernel.py &
RANK=1 INTERMEDIATE_SIZE=6400 CUDA_VISIBLE_DEVICES=1 WORLD_SIZE=4 python tune_kernel.py &
RANK=2 INTERMEDIATE_SIZE=6400 CUDA_VISIBLE_DEVICES=2 WORLD_SIZE=4 python tune_kernel.py &
RANK=3 INTERMEDIATE_SIZE=6400 CUDA_VISIBLE_DEVICES=3 WORLD_SIZE=4 python tune_kernel.py &
wait